In [80]:
import os
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [81]:
csv_file=os.path.join("..","Resources","df_living_wage.csv")
lw = pd.read_csv(csv_file)
lw.head()

,Unnamed: 0,Unnamed: 0_level_0,1 ADULT,1 ADULT.1,1 ADULT.2,1 ADULT.3,2 ADULTS(1 WORKING),2 ADULTS(1 WORKING).1,2 ADULTS(1 WORKING).2,2 ADULTS(1 WORKING).3,2 ADULTS(BOTH WORKING),2 ADULTS(BOTH WORKING).1,2 ADULTS(BOTH WORKING).2,2 ADULTS(BOTH WORKING).3,State,County
0,NaN,Unnamed: 0_level_1,0 Children,1 Child,2 Children,3 Children,0 Children,1 Child,2 Children,3 Children,0 Children,1 Child,2 Children,3 Children,NaN,NaN
1,0.0,Living Wage,$13.58,$27.37,$33.45,$42.19,$22.61,$26.69,$30.29,$32.00,$11.30,$15.07,$18.60,$21.18,Alabama,Autauga County
2,1.0,Poverty Wage,$6.13,$8.29,$10.44,$12.60,$8.29,$10.44,$12.60,$14.75,$4.14,$5.22,$6.30,$7.38,Alabama,Autauga County
3,2.0,Minimum Wage,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,Alabama,Autauga County
4,0.0,Living Wage,$14.73,$28.08,$34.25,$43.94,$22.94,$27.30,$30.90,$33.45,$11.47,$15.42,$19.00,$22.05,Alabama,Baldwin County

In [82]:
lw =  lw.astype("category")
# lw.dtypes
# lw.head()
# list(lw.columns)

In [83]:
lw= lw.drop(["Unnamed: 0"],axis=1)
lw = lw.rename({"Unnamed: 0_level_0":"type"},axis="columns")
lw = lw.rename({"1 ADULT":"1a1w0c","1 ADULT.1":"1a1w1c","1 ADULT.2":"1a1w2c","1 ADULT.3":"1a1w3c"},axis="columns") 
lw = lw.rename({"2 ADULTS(1 WORKING)":"2a1w0c","2 ADULTS(1 WORKING).1":"2a1w1c","2 ADULTS(1 WORKING).2":"2a1w2c","2 ADULTS(1 WORKING).3":"2a1w3c"},axis="columns")
lw = lw.rename({"2 ADULTS(BOTH WORKING)":"2a2w0c","2 ADULTS(BOTH WORKING).1":"2a2w1c","2 ADULTS(BOTH WORKING).2":"2a2w2c","2 ADULTS(BOTH WORKING).3":"2a2w3c"},axis="columns")       
lw= lw.drop([0])
lw.head()

,type,1a1w0c,1a1w1c,1a1w2c,1a1w3c,2a1w0c,2a1w1c,2a1w2c,2a1w3c,2a2w0c,2a2w1c,2a2w2c,2a2w3c,State,County
1,Living Wage,$13.58,$27.37,$33.45,$42.19,$22.61,$26.69,$30.29,$32.00,$11.30,$15.07,$18.60,$21.18,Alabama,Autauga County
2,Poverty Wage,$6.13,$8.29,$10.44,$12.60,$8.29,$10.44,$12.60,$14.75,$4.14,$5.22,$6.30,$7.38,Alabama,Autauga County
3,Minimum Wage,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,Alabama,Autauga County
4,Living Wage,$14.73,$28.08,$34.25,$43.94,$22.94,$27.30,$30.90,$33.45,$11.47,$15.42,$19.00,$22.05,Alabama,Baldwin County
5,Poverty Wage,$6.13,$8.29,$10.44,$12.60,$8.29,$10.44,$12.60,$14.75,$4.14,$5.22,$6.30,$7.38,Alabama,Baldwin County