In [142]:
import pandas as pd

In [143]:
url = "https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/home/?cid=nrcs143_013697"
df = pd.read_html(url)[0]

In [144]:
abbvs = pd.read_html("https://www.bu.edu/brand/guidelines/editorial-style/us-state-abbreviations/",header=0)[0]
df = df.drop(df.index[3232], axis=0)

In [145]:
df = df.rename(columns={'State_Name': 'State'})

In [146]:
abbvs = abbvs.rename(columns={'Full Name':'State'})

In [147]:
lw_data = pd.read_csv("Resources/df_living_wage.csv")
lw_data_factors = pd.read_csv("Resources/df_living_wage_factors.csv")

In [148]:
df = df.dropna(how='any')
lw_data = lw_data.dropna(how='any')
abbvs = abbvs.dropna(how='any')
lw_data_factors = lw_data_factors.dropna(how='any')

In [149]:
abbvs.head()
df_m1 = pd.merge(df, abbvs, on='State')

In [150]:
#merge lw_data and abbreviations on state column
lw_data = lw_data.merge(abbvs,how='left', on='State')

In [151]:
lw_data

,Unnamed: 0,Unnamed: 0_level_0,1 ADULT,1 ADULT.1,1 ADULT.2,1 ADULT.3,2 ADULTS(1 WORKING),2 ADULTS(1 WORKING).1,2 ADULTS(1 WORKING).2,2 ADULTS(1 WORKING).3,2 ADULTS(BOTH WORKING),2 ADULTS(BOTH WORKING).1,2 ADULTS(BOTH WORKING).2,2 ADULTS(BOTH WORKING).3,State,County,Traditional Abbreviation,2-letter USPS
0,0.0,Living Wage,$13.58,$27.37,$33.45,$42.19,$22.61,$26.69,$30.29,$32.00,$11.30,$15.07,$18.60,$21.18,Alabama,Autauga County,Ala.,AL
1,1.0,Poverty Wage,$6.13,$8.29,$10.44,$12.60,$8.29,$10.44,$12.60,$14.75,$4.14,$5.22,$6.30,$7.38,Alabama,Autauga County,Ala.,AL
2,2.0,Minimum Wage,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,Alabama,Autauga County,Ala.,AL
3,0.0,Living Wage,$14.73,$28.08,$34.25,$43.94,$22.94,$27.30,$30.90,$33.45,$11.47,$15.42,$19.00,$22.05,Alabama,Baldwin County,Ala.,AL
4,1.0,Poverty Wage,$6.13,$8.29,$10.44,$12.60,$8.29,$10.44,$12.60,$14.75,$4.14,$5.22,$6.30,$7.38,Alabama,Baldwin County,Ala.,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10573,1.0,Poverty Wage,$6.13,$8.29,$10.44,$12.60,$8.29,$10.44,$12.60,$14.75,$4.14,$5.22,$6.30,$7.38,Wyoming,"Casper, WY",Wyo.,WY
10574,2.0,Minimum Wage,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,Wyoming,"Casper, WY",Wyo.,WY
10575,0.0,Living Wage,$13.67,$27.73,$34.53,$45.17,$21.71,$26.42,$29.97,$33.17,$10.84,$15.28,$19.12,$22.79,Wyoming,"Cheyenne, WY",Wyo.,WY
10576,1.0,Poverty Wage,$6.13,$8.29,$10.44,$12.60,$8.29,$10.44,$12.60,$14.75,$4.14,$5.22,$6.30,$7.38,Wyoming,"Cheyenne, WY",Wyo.,WY
10577,2.0,Minimum Wage,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,Wyoming,"Cheyenne, WY",Wyo.,WY

In [177]:
lw_data["lookup"] = lw_data['County'].replace("County",None)

In [178]:
lw_data.head()

,Unnamed: 0,Unnamed: 0_level_0,1 ADULT,1 ADULT.1,1 ADULT.2,1 ADULT.3,2 ADULTS(1 WORKING),2 ADULTS(1 WORKING).1,2 ADULTS(1 WORKING).2,2 ADULTS(1 WORKING).3,2 ADULTS(BOTH WORKING),2 ADULTS(BOTH WORKING).1,2 ADULTS(BOTH WORKING).2,2 ADULTS(BOTH WORKING).3,State,County,Traditional Abbreviation,2-letter USPS,lookup
0,0.0,Living Wage,$13.58,$27.37,$33.45,$42.19,$22.61,$26.69,$30.29,$32.00,$11.30,$15.07,$18.60,$21.18,Alabama,Autauga County,Ala.,AL,Autauga County
1,1.0,Poverty Wage,$6.13,$8.29,$10.44,$12.60,$8.29,$10.44,$12.60,$14.75,$4.14,$5.22,$6.30,$7.38,Alabama,Autauga County,Ala.,AL,Autauga County
2,2.0,Minimum Wage,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,$7.25,Alabama,Autauga County,Ala.,AL,Autauga County
3,0.0,Living Wage,$14.73,$28.08,$34.25,$43.94,$22.94,$27.30,$30.90,$33.45,$11.47,$15.42,$19.00,$22.05,Alabama,Baldwin County,Ala.,AL,Baldwin County
4,1.0,Poverty Wage,$6.13,$8.29,$10.44,$12.60,$8.29,$10.44,$12.60,$14.75,$4.14,$5.22,$6.30,$7.38,Alabama,Baldwin County,Ala.,AL,Baldwin County